### ISSUE TITLE
I have find a Reflected XSS vulnerability in this project

### ISSUE THREAD

**Issue by jgj212** [groovel/cmsgroovel#2]
Hello:
I have find a Reflected XSS vulnerability in this project.

The vulnerability exists due to insufficient filtration of user-supplied data in “path” HTTP parameter that will be passed to “cmsgroovel-master/src/commons/browser.php”. The infected source code is line 26, there is no protection on $_REQUEST['path']; if $_REQUEST['path'] contains evil js code, line 29 will trigger untrusted code to be excuted on the browser side.
![code1](https://cloud.githubusercontent.com/assets/1484292/23576401/418d4b86-00df-11e7-95d8-20e38c4798e0.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/cmsgroovel-master/src/commons/browser.php?path="><script>alert(1);</script><"

The follow scrrenshot is the result to click the upper url ( win7 spq x64 + firefox 51.0.1 32bit ):
![sc](https://cloud.githubusercontent.com/assets/1484292/23576404/4b0a99c0-00df-11e7-9630-9e6469f48ac2.png)

Discoverer: Haojun Hou, DongWang in ADLab of Venustech

**Comment by groovel** [comment]
Hi thanks for your contribution, the issue , yes well done i see it , i don t use anymore the class browser.php, i drop it from the projects.
